
var textDatabase = [
  "a razão nasce da emoção e vive de sua morte",
  'pepeca pepeca sangra pepeca. peca ate o papa peca',
  "But you're still hungry.",
  'eu odeio o final de vampiras lésbicas',
  'estamos assistindo sua live pelo wifi da renner',
  'a vagabunda que falou mal da minha sobrancelha vai tomar no cu',
  'Anitta dona da chave de sodoma e gomorra',
  'IAN MEU AMRZINHO',
  //'MANU MINHA VIDINHA',
  'pra quem voce ligaria se pudesse ligar pra qualquer pessoa agora',
  'sinto saudades do cheiro de buxinho do meu gato',
  'hoje sonhei que as minhas pernas nao eram minhas',
  "o que é individualidade?",
  "hoje sonhei que eu tava fazendo pão",
  "transmissão",
  "oieeeee ihihihihiiiii td bommm",
  "ideal platonico de um cachorro",
  "hoje acordei com dedos...",
  "SEM MOVIMENTO NÃO HÁ VIDA",
  "chupa meu bucetao",
  "ihihihhihihih",
  "digimonas",
  "voce está comendo chocolate",
  "pizza de lua",
  "nao sei o que escrever kkkk desculpa",
  "no que você está pensando?",
  "JOGUE SILKSONG",
  "e pegue e puxe e pegue e naipe e naipe naipe e naipe naipe",
  "devaneios estranhos...",
  "SKAAAAASJDHAKSHS FDSAJFHAFHDSH SHFJXNSFAHFGSAAAAdsdfdfdg",
  "tem maluco pra tudoooooo",
  ":3 <3 0.0 <(*_*)/",
  ":^^{``@*&&¨&¨&%&¨¨/?(**!@##",
  "to morrendo de vontade de comer bolo de cenoura :(",
  "tô com saudade",
  "O QUE QUE VOCE TA OLHANDO?",
  "assista knights of guinevere!!!!!!",
  "NÃO CONFUNDA as grandes obras do mestre picasso com a grande pica de aço do mestre de obras!!",
  "eu literalmente só queria dormir",
  "queria que alguém fizesse cafuné em mim",
  "eu amo ser artista!!!"
];
